<a href="https://colab.research.google.com/github/Taeseon-Baek/AI_Project/blob/main/AI_teamproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
import pandas as pd
columns = ['duration','protocol_type','service','flag','src_bytes','dst_bytes','land','wrong_fragment','urgent','hot','num_failed_logins','logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files','num_outbound_cmds','is_host_login','is_guest_login','count','srv_count','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate','diff_srv_rate','srv_diff_host_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_srv_diff_host_rate','dst_host_serror_rate','dst_host_srv_serror_rate','dst_host_rerror_rate','dst_host_srv_rerror_rate','label','difficulty_level']
data = pd.read_csv('/content/gdrive/MyDrive/Colab_Notebooks/kddcup.data',names=columns)

In [ ]:
data

         duration protocol_type  ...    label difficulty_level
0               0           tcp  ...  normal.              NaN
1               0           tcp  ...  normal.              NaN
2               0           tcp  ...  normal.              NaN
3               0           tcp  ...  normal.              NaN
4               0           tcp  ...  normal.              NaN
...           ...           ...  ...      ...              ...
4898426         0           tcp  ...  normal.              NaN
4898427         0           tcp  ...  normal.              NaN
4898428         0           tcp  ...  normal.              NaN
4898429         0           tcp  ...  normal.              NaN
4898430         0           tcp  ...  normal.              NaN

[4898431 rows x 43 columns]

In [ ]:
change_value_dict = {'back.':'dos','buffer_overflow.':'u2r','ftp_write.':'r2l','guess_passwd':'r2l','imap':'r2l','ipsweep':'probe','land':'dos','loadmodule':'u2r','multihop':'r2l','neptune':'dos','nmap':'probe','perl':'u2r','phf':'r2l','pod':'dos','portsweep':'probe','rootkit':'u2r','satan':'probe','smurf':'dos','spy':'r2l','teardrop':'dos','warezclient':'r2l','warezmaster':'r2l','normal':'normal'}
data = data.replace({'label':change_value_dict})

In [ ]:
len(set(data.iloc[:,-1]))

In [ ]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
data['label'] = LE.fit_transform(data['label']) 
set(data.iloc[:,-1])

In [ ]:
LE = LabelEncoder()
data['protocol_type'] = LE.fit_transform(data['protocol_type'])
LE = LabelEncoder()
data['service'] = LE.fit_transform(data['service']) 
LE = LabelEncoder()
data['flag'] = LE.fit_transform(data['flag'])

In [ ]:
from sklearn.model_selection import train_test_split
x, x_test, y, testY = train_test_split(data.iloc[:,:-1],data.iloc[:,-1], test_size=0.2) #8:2 비율

In [ ]:
import matplotlib.pyplot as plt
count_classes = pd.value_counts(y, sort = True,normalize=True).sort_index()
print(count_classes*100)
# 클래스별 데이터 분포 확인
count_classes.plot(kind = 'bar')
plt.title("class histogram")
plt.xlabel("Class")
plt.ylabel("Frequency")

In [ ]:
import numpy as np
#Class Weight 계산
from sklearn.utils import class_weight
class_weight = class_weight.compute_class_weight(class_weight='balanced',classes=np.unique(y),y=y)
class_weight = dict(zip(np.unique(Y), class_weight))
class_weight